import { useMemo } from "react";
import { APP_MODES } from "../utils/constants";

/**
 * Hook to memoize toolbar props for MainLayout
 *
 * Centralizes all props needed by the ContextToolbar component
 * to improve code organization and prevent unnecessary re-renders.
 *
 * @param {Object} params - All toolbar-related state and handlers
 * @returns {Object} - Memoized toolbar props object
 */
export function useToolbarProps({
  appMode,
  contextCounts,
  filterMode,
  setFilterMode,
  filterByCreator,
  setFilterByCreator,
  filterTags,
  setFilterTags,
  filterScoreTier,
  setFilterScoreTier,
  filterByReviewer,
  setFilterByReviewer,
  uniqueReviewers,
  customTags,
  searchTerm,
  setSearchTerm,
  sortBy,
  setSortBy,
  isProcessing,
  status,
  isAuthReady,
  config,
  handleLoadFromSheets,
  handleLoadFromFirestore,
  setShowBulkExportModal,
  handleClearPending,
  handleBulkAcceptHighScores,
  handleBulkCritiqueAll,
  handleTrimExcess,
  handleAutoTagAll,
  effectiveApiKey,
  handleChange,
}) {
  return useMemo(
    () => ({
      mode: appMode,
      counts: contextCounts,
      filterMode,
      setFilterMode,
      filterByCreator,
      setFilterByCreator,
      filterTags,
      setFilterTags,
      filterScoreTier,
      setFilterScoreTier,
      filterByReviewer,
      setFilterByReviewer,
      uniqueReviewers,
      customTags,
      searchTerm,
      setSearchTerm,
      sortBy,
      setSortBy,
      isProcessing,
      status,
      isAuthReady,
      config,
      onLoadSheets: handleLoadFromSheets,
      onLoadFirestore: handleLoadFromFirestore,
      onBulkExport: () => setShowBulkExportModal(true),
      onClearPending: handleClearPending,
      onBulkAcceptHighScores:
        appMode === APP_MODES.REVIEW ? handleBulkAcceptHighScores : undefined,
      onBulkCritiqueAll:
        appMode === APP_MODES.REVIEW ? handleBulkCritiqueAll : undefined,
      onTrimExcess: handleTrimExcess,
      onAutoTagAll: handleAutoTagAll,
      effectiveApiKey,
      handleChange,
    }),
    [
      appMode,
      contextCounts,
      filterMode,
      setFilterMode,
      filterByCreator,
      setFilterByCreator,
      filterTags,
      setFilterTags,
      filterScoreTier,
      setFilterScoreTier,
      filterByReviewer,
      setFilterByReviewer,
      uniqueReviewers,
      customTags,
      searchTerm,
      setSearchTerm,
      sortBy,
      setSortBy,
      isProcessing,
      status,
      isAuthReady,
      config,
      handleLoadFromSheets,
      handleLoadFromFirestore,
      setShowBulkExportModal,
      handleClearPending,
      handleBulkAcceptHighScores,
      handleBulkCritiqueAll,
      handleTrimExcess,
      handleAutoTagAll,
      effectiveApiKey,
      handleChange,
    ]
  );
}
