import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  BarChart2,
  Bomb,
  BookOpen,
  Bot,
  Calculator,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Clipboard,
  ClipboardList,
  Clock,
  CloudDownload,
  CloudLightning,
  Copy,
  CornerUpLeft,
  Cpu,
  Database,
  DollarSign,
  Download,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  FileMinus,
  FileText,
  Filter,
  Flag,
  Folder,
  GitBranch,
  GitCompare,
  GitMerge,
  Globe,
  Hash,
  HelpCircle,
  Inbox,
  Info,
  Key,
  Languages,
  LayoutDashboard,
  Layers,
  Lightbulb,
  Link,
  Link2,
  List,
  ListChecks,
  Loader,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  PieChart,
  Play,
  Plug,
  Plus,
  PlusCircle,
  RefreshCw,
  Save,
  Search,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Slash,
  Sliders,
  Sparkles,
  Star,
  Table,
  Tag,
  Target,
  Terminal,
  ThumbsDown,
  Trash,
  Trash2,
  Type,
  Unlink,
  UploadCloud,
  User,
  UserCheck,
  Users,
  Unlock,
  Wand,
  WifiOff,
  Wrench,
  X,
  XCircle,
  Zap,
  ClipboardCheck,
  ShieldX,
} from "lucide-react";
import { logger } from "../utils/logger";

const ICON_MAP = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-octagon": AlertOctagon,
  "alert-triangle": AlertTriangle,
  archive: Archive,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  award: Award,
  "bar-chart-2": BarChart2,
  bomb: Bomb,
  bot: Bot,
  "book-open": BookOpen,
  calculator: Calculator,
  check: Check,
  "check-circle": CheckCircle,
  "check-shield": ShieldCheck,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  clipboard: Clipboard,
  "clipboard-list": ClipboardList,
  clock: Clock,
  "cloud-download": CloudDownload,
  "cloud-lightning": CloudLightning,
  copy: Copy,
  "corner-up-left": CornerUpLeft,
  cpu: Cpu,
  database: Database,
  "dollar-sign": DollarSign,
  download: Download,
  edit: Edit,
  "edit-2": Edit2,
  "edit-3": Edit3,
  "external-link": ExternalLink,
  eye: Eye,
  "file-minus": FileMinus,
  "file-text": FileText,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  "git-branch": GitBranch,
  "git-compare": GitCompare,
  "layout-dashboard": LayoutDashboard,
  "git-merge": GitMerge,
  globe: Globe,
  hash: Hash,
  "help-circle": HelpCircle,
  inbox: Inbox,
  info: Info,
  key: Key,
  languages: Languages,
  layers: Layers,
  lightbulb: Lightbulb,
  link: Link,
  "link-2": Link2,
  list: List,
  "list-checks": ListChecks,
  loader: Loader,
  lock: Lock,
  unlock: Unlock,
  "log-out": LogOut,
  mail: Mail,
  menu: Menu,
  "message-square": MessageSquare,
  "pie-chart": PieChart,
  play: Play,
  plug: Plug,
  plus: Plus,
  "plus-circle": PlusCircle,
  "refresh-cw": RefreshCw,
  save: Save,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  slash: Slash,
  sliders: Sliders,
  sparkles: Sparkles,
  star: Star,
  table: Table,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  "thumbs-down": ThumbsDown,
  trash: Trash,
  "trash-2": Trash2,
  type: Type,
  unlink: Unlink,
  "upload-cloud": UploadCloud,
  user: User,
  "user-check": UserCheck,
  users: Users,
  wand: Wand,
  "wifi-off": WifiOff,
  wrench: Wrench,
  x: X,
  "x-circle": XCircle,
  zap: Zap,
  "clipboard-check": ClipboardCheck,
  "shield-x": ShieldX,
};

const DEFAULT_ICON_SIZE = 16;

const Icon = ({
  name,
  size = DEFAULT_ICON_SIZE,
  className = "",
  ariaLabel,
  role,
}) => {
  // Direct lookup in the icon map for speed and tree-shakability
  const LucideIcon = ICON_MAP[name.toLowerCase()];

  if (!LucideIcon) {
    logger.warn(
      `Icon "${name}" not found in refactored ICON_MAP. Please add it.`
    );
    return (
      <span style={{ width: size, height: size, display: "inline-block" }} />
    );
  }

  return (
    <LucideIcon
      size={size}
      className={className}
      aria-label={ariaLabel}
      aria-hidden={!ariaLabel}
      role={role || (ariaLabel ? "img" : "presentation")}
    />
  );
};

export default Icon;
