import React from 'react';
import { AlertTriangle, Shield, Info } from 'lucide-react';

/**
 * Terms of Use Modal - First-time user acceptance
 * Covers liability, disclaimers, and educational use
 */
const TermsOfUseModal = ({ isOpen, onAccept, onDecline }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm p-4 animate-in fade-in duration-200">
            <div className="bg-slate-900 border border-yellow-500 w-full max-w-4xl max-h-[90vh] rounded-xl shadow-2xl overflow-hidden">

                {/* Header */}
                <div className="bg-gradient-to-r from-yellow-600 to-orange-600 p-6 flex items-center gap-4">
                    <AlertTriangle className="w-10 h-10 text-white" />
                    <div>
                        <h2 className="text-2xl font-bold text-white">Terms of Use & Legal Disclaimer</h2>
                        <p className="text-sm text-yellow-100">Please read carefully before using this tool</p>
                    </div>
                </div>

                {/* Content - Scrollable */}
                <div className="p-6 overflow-y-auto max-h-[60vh] space-y-6 text-slate-200">

                    {/* Disclaimer */}
                    <section className="bg-red-900/20 border border-red-700 rounded-lg p-4">
                        <h3 className="text-lg font-bold text-red-400 flex items-center gap-2 mb-3">
                            <AlertTriangle size={20} />
                            IMPORTANT DISCLAIMER
                        </h3>
                        <p className="text-sm leading-relaxed">
                            This tool is provided <strong>"AS IS"</strong> for educational purposes only.
                            Epic Games, Inc. and the tool creator make <strong>NO WARRANTIES</strong> about
                            the accuracy, completeness, reliability, or suitability of AI-generated content.
                        </p>
                    </section>

                    {/* Instructor Responsibility */}
                    <section>
                        <h3 className="text-lg font-bold text-blue-400 flex items-center gap-2 mb-3">
                            <Shield size={20} />
                            Instructor Responsibility
                        </h3>
                        <ul className="text-sm space-y-2 list-disc list-inside">
                            <li>You are <strong>solely responsible</strong> for reviewing all AI-generated questions</li>
                            <li>You must verify <strong>technical accuracy</strong> before using in assessments</li>
                            <li>You accept <strong>full liability</strong> for any content you approve and deploy</li>
                            <li>Epic Games is NOT responsible for errors in AI-generated content</li>
                        </ul>
                    </section>

                    {/* AI Content Notice */}
                    <section>
                        <h3 className="text-lg font-bold text-purple-400 flex items-center gap-2 mb-3">
                            <Info size={20} />
                            AI-Generated Content
                        </h3>
                        <p className="text-sm leading-relaxed">
                            Questions are generated by <strong>Google Gemini AI</strong> and may contain:
                        </p>
                        <ul className="text-sm space-y-1 list-disc list-inside mt-2">
                            <li>Hallucinations or factual errors</li>
                            <li>Outdated information</li>
                            <li>Broken or incorrect source URLs</li>
                            <li>Inappropriate difficulty levels</li>
                        </ul>
                        <p className="text-sm mt-2 font-semibold text-yellow-400">
                            ⚠ Human review is MANDATORY before use in any assessment.
                        </p>
                    </section>

                    {/* Liability Limitation */}
                    <section>
                        <h3 className="text-lg font-bold text-slate-300 mb-3">Limitation of Liability</h3>
                        <p className="text-xs leading-relaxed bg-slate-800 p-3 rounded">
                            TO THE MAXIMUM EXTENT PERMITTED BY LAW, EPIC GAMES, INC. AND THE TOOL CREATOR
                            SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
                            OR EXEMPLARY DAMAGES ARISING FROM USE OF THIS TOOL, INCLUDING BUT NOT LIMITED TO:
                            DAMAGES FOR LOSS OF DATA, INACCURATE ASSESSMENTS, STUDENT DISPUTES, OR ANY OTHER
                            MATTER RELATING TO THE USE OF AI-GENERATED CONTENT.
                        </p>
                    </section>

                    {/* Authorized Users Only */}
                    <section>
                        <h3 className="text-lg font-bold text-green-400 mb-3">Authorized Users</h3>
                        <p className="text-sm">
                            This tool is intended for <strong>Unreal Engine Authorized Instructors</strong> only.
                            By using this tool, you represent that you are:
                        </p>
                        <ul className="text-sm space-y-1 list-disc list-inside mt-2">
                            <li>At least 18 years of age</li>
                            <li>A certified Unreal Engine instructor or educator</li>
                            <li>Authorized to create educational content for Unreal Engine training</li>
                            <li>Compliant with Epic Games' Authorized Instructor Program terms</li>
                        </ul>
                    </section>

                    {/* Data Privacy */}
                    <section>
                        <h3 className="text-lg font-bold text-blue-400 mb-3">Privacy & Data</h3>
                        <p className="text-sm">
                            Your data is processed according to our Privacy Policy. Key points:
                        </p>
                        <ul className="text-sm space-y-1 list-disc list-inside mt-2">
                            <li>Data stored in Google Firebase (USA)</li>
                            <li>Questions sent to Google Gemini AI for generation</li>
                            <li>LocalStorage encrypted with AES-256</li>
                            <li>You can export or delete your data anytime</li>
                        </ul>
                        <p className="text-xs mt-2">
                            See <strong>LICENSES.md</strong> for full privacy details and GDPR rights.
                        </p>
                    </section>

                    {/* Agreement */}
                    <section className="bg-slate-800 border border-slate-600 rounded-lg p-4 mt-6">
                        <p className="text-sm font-semibold text-white">
                            By clicking "I Accept", you acknowledge that you have read, understood, and agree to:
                        </p>
                        <ul className="text-xs space-y-1 mt-2">
                            <li>✓ These Terms of Use</li>
                            <li>✓ The Disclaimer of Warranties</li>
                            <li>✓ The Limitation of Liability</li>
                            <li>✓ Your responsibility to review all AI-generated content</li>
                            <li>✓ Epic Games' Privacy Policy and Data Processing practices</li>
                        </ul>
                    </section>
                </div>

                {/* Footer - Action Buttons */}
                <div className="bg-slate-800 border-t border-slate-700 p-6 flex justify-between items-center">
                    <button
                        onClick={onDecline}
                        className="px-6 py-3 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg transition-colors"
                    >
                        Decline (Exit)
                    </button>
                    <button
                        onClick={onAccept}
                        className="px-8 py-3 bg-green-600 hover:bg-green-700 text-white font-bold rounded-lg transition-colors shadow-lg"
                    >
                        I Accept - Continue to Tool
                    </button>
                </div>
            </div>
        </div>
    );
};

export default TermsOfUseModal;
